### ISSUE TITLE
core_completion\progress class not found

### ISSUE THREAD

**Issue by dustinbrisebois** [mudrd8mz/moodle-mod_subcourse#36]
Have found in some cases the class core_completion\progress is not found - by adding the following class require check this issue goes away

https://github.com/mudrd8mz/moodle-mod_subcourse/pull/35

**Comment by mudrd8mz** [comment]
As commented in the pull request - are you able to provide steps to reproduce the situation when the class is not found? Because it should really never happen, given that it is the autoloaded class (https://docs.moodle.org/dev/Automatic_class_loading)

I suspect there must be something else happening there.
