### ISSUE TITLE
Is Fetch_Grades Run Time > 2 minutes normal

### ISSUE THREAD

**Issue by peverist** [mudrd8mz/moodle-mod_subcourse#46]
Hi

I have noted the Fetch_Grades task in my moodle system is typically taking between 2 minutes and 3 minutes to execute - is that normal?  
Moodle 3.10
Users: approx 18,000

[mod_subcourse_task_fetch_grades-139845.log](https://github.com/mudrd8mz/moodle-mod_subcourse/files/6620799/mod_subcourse_task_fetch_grades-139845.log)
![subcourse tasks logs1](https://user-images.githubusercontent.com/75293765/121286240-e69c3500-c922-11eb-82a1-68ea3831d49a.jpg)

Thanks
Phil

**Comment by mudrd8mz** [comment]
Hi Phil. Yes - this scheduled task is known to take quite a long time. In the early versions of the module, it was the only way to get grades synced. But since then, the module has improved a lot performance-wise and in most cases, the grades are synced for individual students via events.

This scheduled task remained as kind of last resort to sync grades that would be missed for whatever reason. As such, there is no need to run it too frequently and by default, this task should be executed just once a day. From the screenshot it seems you are running it way more often and I don't think there is a need for it.
